import { Product, Category, Weather, Article, MarketPrice, User, Order, Review } from './types';

// Updated common image URL with higher quality agriculture image
const DEFAULT_IMAGE = 'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80';

// Product images
const PRODUCT_IMAGES = {
  tomatoes: 'https://images.unsplash.com/photo-1592924357520-e34c697351e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  apples: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  rice: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  milk: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  hoe: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  seeds: 'https://images.unsplash.com/photo-1574491825371-85a4e7acce99?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  fertilizer: 'https://images.unsplash.com/photo-1585202900225-6d3ac20a6962?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  tiller: 'https://images.unsplash.com/photo-1568555622465-98e4316dd19b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  carrots: 'https://images.unsplash.com/photo-1522184216316-3c1a2f3fc8cc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  bananas: 'https://images.unsplash.com/photo-1543218024-57a70143c369?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
};

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Vegetables', icon: 'leaf' },
  { id: '2', name: 'Fruits', icon: 'apple-alt' },
  { id: '3', name: 'Grains', icon: 'seedling' },
  { id: '4', name: 'Dairy', icon: 'cheese' },
  { id: '5', name: 'Tools', icon: 'tools' },
  { id: '6', name: 'Seeds', icon: 'spa' },
  { id: '7', name: 'Fertilizers', icon: 'prescription-bottle' },
  { id: '8', name: 'Machinery', icon: 'tractor' },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    price: 120,
    image: PRODUCT_IMAGES.tomatoes,
    description: 'Fresh organic tomatoes grown without pesticides. Perfect for salads and cooking.',
    category: 'Vegetables',
    rating: 4.5,
  },
  {
    id: '2',
    name: 'Red Apples',
    price: 180,
    image: PRODUCT_IMAGES.apples,
    description: 'Sweet and juicy red apples. Rich in antioxidants and fiber.',
    category: 'Fruits',
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Basmati Rice (5kg)',
    price: 850,
    image: PRODUCT_IMAGES.rice,
    description: 'Premium quality aromatic basmati rice. Long grain and naturally fragrant.',
    category: 'Grains',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Fresh Milk (1L)',
    price: 220,
    image: PRODUCT_IMAGES.milk,
    description: 'Fresh cow milk. Rich in calcium and protein.',
    category: 'Dairy',
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Garden Hoe',
    price: 1200,
    image: PRODUCT_IMAGES.hoe,
    description: 'Durable garden hoe with ergonomic handle. Perfect for weeding and cultivating soil.',
    category: 'Tools',
    rating: 4.4,
  },
  {
    id: '6',
    name: 'Organic Cucumber Seeds',
    price: 150,
    image: PRODUCT_IMAGES.seeds,
    description: 'High-quality cucumber seeds for organic farming. High germination rate.',
    category: 'Seeds',
    rating: 4.3,
  },
  {
    id: '7',
    name: 'Organic Fertilizer (5kg)',
    price: 950,
    image: PRODUCT_IMAGES.fertilizer,
    description: 'Natural organic fertilizer enriched with essential nutrients for plant growth.',
    category: 'Fertilizers',
    rating: 4.5,
  },
  {
    id: '8',
    name: 'Mini Tiller',
    price: 25000,
    image: PRODUCT_IMAGES.tiller,
    description: 'Compact and powerful mini tiller for small to medium gardens. Efficient soil cultivation.',
    category: 'Machinery',
    rating: 4.7,
  },
  {
    id: '9',
    name: 'Carrots',
    price: 110,
    image: PRODUCT_IMAGES.carrots,
    description: 'Fresh and crunchy carrots rich in beta-carotene and fiber.',
    category: 'Vegetables',
    rating: 4.5,
  },
  {
    id: '10',
    name: 'Bananas',
    price: 130,
    image: PRODUCT_IMAGES.bananas,
    description: 'Sweet and nutritious bananas. Rich in potassium and vitamin B6.',
    category: 'Fruits',
    rating: 4.6,
  },
];

export const WEATHER: Weather[] = [
  {
    location: 'Colombo',
    temperature: 30,
    condition: 'Sunny',
    humidity: 70,
    date: new Date(),
  },
  {
    location: 'Kandy',
    temperature: 26,
    condition: 'Partly Cloudy',
    humidity: 65,
    date: new Date(),
  },
  {
    location: 'Anuradhapura',
    temperature: 32,
    condition: 'Sunny',
    humidity: 60,
    date: new Date(),
  },
  {
    location: 'Nuwara Eliya',
    temperature: 20,
    condition: 'Light Rain',
    humidity: 85,
    date: new Date(),
  },
  {
    location: 'Jaffna',
    temperature: 29,
    condition: 'Sunny',
    humidity: 55,
    date: new Date(),
  },
];

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Sustainable Farming Practices',
    summary: 'Learn about eco-friendly approaches to farming that can improve yields while protecting the environment.',
    content: 'Sustainable farming practices focus on long-term ecological balance, utilizing methods that maintain soil health, minimize water usage, and reduce dependence on non-renewable resources. These techniques include crop rotation, using natural fertilizers, integrated pest management, and minimizing tillage. By adopting these practices, farmers can increase resilience to climate change, improve biodiversity, enhance soil fertility, and ultimately achieve better long-term yields while reducing their environmental footprint.',
    image: DEFAULT_IMAGE,
    author: 'Dr. Amali Fernando',
    date: new Date('2023-11-15'),
    tags: ['sustainable', 'eco-friendly', 'farming'],
  },
  {
    id: '2',
    title: 'Maximizing Rice Yields',
    summary: 'Tips and techniques for increasing rice production while maintaining quality.',
    content: 'Rice is one of the most important food crops in Sri Lanka, and maximizing yields while maintaining quality is crucial for food security and farmer prosperity. This article explores advanced techniques like System of Rice Intensification (SRI), proper water management, optimal fertilization schedules, and effective pest control. These methods can help farmers achieve up to 30% higher yields while reducing input costs. The article also covers post-harvest handling to minimize losses and maintain grain quality.',
    image: DEFAULT_IMAGE,
    author: 'Pradeep Kumara',
    date: new Date('2023-12-01'),
    tags: ['rice', 'yields', 'farming techniques'],
  },
  {
    id: '3',
    title: 'Weather Patterns and Crop Planning',
    summary: 'Understanding seasonal weather patterns to optimize crop planning and mitigate risks.',
    content: 'Climate change has made traditional farming calendars less reliable, requiring farmers to adapt their crop planning approaches. This article provides insight into interpreting weather forecasts, identifying micro-climate patterns in your farm, and selecting appropriate crop varieties based on expected conditions. It also covers strategies for mitigating risks from extreme weather events and making the most of favorable conditions. By aligning planting schedules with weather patterns, farmers can significantly improve yields and reduce crop losses.',
    image: DEFAULT_IMAGE,
    author: 'Nimal Perera',
    date: new Date('2024-01-10'),
    tags: ['weather', 'crop planning', 'climate change'],
  },
  {
    id: '4',
    title: 'Benefits of Organic Farming',
    summary: 'Exploring the economic and environmental advantages of transitioning to organic farming methods.',
    content: 'Organic farming offers numerous benefits beyond just premium pricing for products. This article explores how organic methods can improve soil health over time, reduce long-term costs, and create more resilient farming systems. It also discusses the certification process, marketing strategies for organic produce, and realistic expectations during the transition period. Case studies of successful Sri Lankan organic farmers demonstrate the practical application of these methods in local conditions.',
    image: DEFAULT_IMAGE,
    author: 'Kumari Weerasinghe',
    date: new Date('2024-02-05'),
    tags: ['organic', 'sustainable', 'certification'],
  },
  {
    id: '5',
    title: 'Water Conservation in Agriculture',
    summary: 'Effective methods for reducing water usage while maintaining or improving crop yields.',
    content: 'Water scarcity is becoming an increasingly important issue for Sri Lankan agriculture. This article covers practical water conservation techniques including drip irrigation, rainwater harvesting, mulching, and selecting drought-resistant crop varieties. It also discusses scheduling irrigation based on actual crop needs rather than fixed schedules. These approaches can reduce water usage by up to 60% while maintaining or even improving yields. The economic analysis shows that while some methods require initial investment, they typically pay for themselves within 1-3 growing seasons.',
    image: DEFAULT_IMAGE,
    author: 'Dr. Ranjith Silva',
    date: new Date('2024-02-25'),
    tags: ['water conservation', 'irrigation', 'efficiency'],
  },
];

export const MARKET_PRICES: MarketPrice[] = [
  {
    id: '1',
    productName: 'Rice (Nadu)',
    price: 150,
    market: 'Colombo Central',
    date: new Date(),
  },
  {
    id: '2',
    productName: 'Rice (Samba)',
    price: 165,
    market: 'Colombo Central',
    date: new Date(),
  },
  {
    id: '3',
    productName: 'Tomatoes',
    price: 120,
    market: 'Dambulla',
    date: new Date(),
  },
  {
    id: '4',
    productName: 'Green Chilies',
    price: 450,
    market: 'Dambulla',
    date: new Date(),
  },
  {
    id: '5',
    productName: 'Potatoes',
    price: 180,
    market: 'Nuwara Eliya',
    date: new Date(),
  },
  {
    id: '6',
    productName: 'Coconuts',
    price: 75,
    market: 'Colombo Central',
    date: new Date(),
  },
];

export const USERS: User[] = [
  {
    id: '1',
    name: 'Sampath Perera',
    email: 'sampath@example.com',
    phone: '0771234567',
    address: '123 Main St, Colombo',
    avatar: DEFAULT_IMAGE,
  },
];

export const ORDERS: Order[] = [
  {
    id: '1',
    userId: '1',
    products: [
      { ...PRODUCTS[0], quantity: 2 },
      { ...PRODUCTS[3], quantity: 1 },
    ],
    totalAmount: 460,
    status: 'delivered',
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2023-12-12'),
  },
  {
    id: '2',
    userId: '1',
    products: [
      { ...PRODUCTS[4], quantity: 1 },
      { ...PRODUCTS[6], quantity: 2 },
    ],
    totalAmount: 3100,
    status: 'processing',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-16'),
  },
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: '1',
    userName: 'Sampath Perera',
    rating: 4,
    text: 'These tomatoes are very fresh and tasty. I use them regularly for my cooking.',
    date: new Date('2023-10-15'),
  },
  {
    id: '2',
    productId: '1',
    userId: '3',
    userName: 'Nimal Fernando',
    rating: 5,
    text: 'Excellent quality! The tomatoes are juicy and flavorful. Will buy again.',
    date: new Date('2023-11-20'),
  },
  {
    id: '3',
    productId: '2',
    userId: '2',
    userName: 'Kumari Silva',
    rating: 5,
    text: 'These apples are delicious and crispy. My kids love them!',
    date: new Date('2023-12-05'),
  },
  {
    id: '4',
    productId: '3',
    userId: '4',
    userName: 'Pradeep Jayawardena',
    rating: 4,
    text: 'Good quality rice. Cooks well and has nice aroma.',
    date: new Date('2024-01-10'),
  },
  {
    id: '5',
    productId: '5',
    userId: '1',
    userName: 'Sampath Perera',
    rating: 5,
    text: 'Very durable garden hoe. Makes my gardening work much easier.',
    date: new Date('2024-02-15'),
  },
  {
    id: '6',
    productId: '5',
    userId: '3',
    userName: 'Nimal Fernando',
    rating: 4,
    text: 'Good quality tool for the price. Handle is comfortable to use.',
    date: new Date('2024-02-28'),
  },
  {
    id: '7',
    productId: '7',
    userId: '2',
    userName: 'Kumari Silva',
    rating: 5,
    text: 'This fertilizer works wonders! My plants are much healthier now.',
    date: new Date('2024-03-05'),
  },
  {
    id: '8',
    productId: '8',
    userId: '4',
    userName: 'Pradeep Jayawardena',
    rating: 5,
    text: 'The mini tiller is perfect for my small farm. Easy to operate and very efficient.',
    date: new Date('2024-03-20'),
  },
];

export default {
  CATEGORIES,
  PRODUCTS,
  WEATHER,
  ARTICLES,
  MARKET_PRICES,
  USERS,
  ORDERS,
  REVIEWS,
}; 